version: "2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /home/node
    volumes:
       - .:/home/node
       - /home/node/node_modules
    
    ports:
      - "9000:9000"
      - "3000:3000"
      